server:
  port: ${config.port:8081}
spring:
  application:
    name: leo-server-4-0-2
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.111.4.49/ufrog_leo_dev?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false
    username: dev
    password: mMZc%j13l
  jpa:
    database: mysql
    showSql: true
logging:
  level:
    root: info
eureka:
  instance:
    preferIpAddress: true
    leaseExpirationDurationInSeconds: 15
    leaseRenewalIntervalInSeconds: 5
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://10.111.4.49:8002/eureka/,http://10.111.4.49:8003/eureka/,http://10.111.4.49:8001/eureka/
ufrog:
  app:
    enabled: true
    secret: zbh7DN0sLZYI5d6L0NzCwklr0NtZExi3RJ6ERKrjIzYuGz6WZYjplu2J0tKqEA8T
    messages: classpath:messages-domain,classpath:messages-service,classpath:messages
    logger:
      caller: true
  pattern:
    uuid: "[0-9a-f]{8}(-[0-9a-f]{4}){3}-[0-9a-f]{12}"
    cellphone: "1[3578][0-9]{9}"
    email: "[\\w!#$%&'*+/=?^_`{|}~-]+(?:\\.[\\w!#$%&'*+/=?^_`{|}~-]+)*@(?:[\\w](?:[\\w-]*[\\w])?\\.)+[a-zA-Z0-9](?:[\\w-]*[\\w])?"
  path:
    resource:
      common: //10.111.4.49:800/leo/resources
      host: //10.111.4.49:800/leo/resources/leo
  cache:
    default:
      duration: 4h
      prefix: leo_
    redis:
      server: 10.111.4.49:2181
      proxy.dir: /jodis/codis-test
      serializer: net.ufrog.common.redis.serializers.ByteArraySerializer
      type: net.ufrog.common.redis.CodisCacheImpl
  client:
    resultCodeClass: net.ufrog.leo.client.contracts.ResultCode
  leo:
    host: http://127.0.0.1:8080
    accessTokenManager: net.ufrog.leo.server.accesstoken.MemAccessTokenManager
    #accessTokenManager: net.ufrog.leo.server.accesstoken.CodisAccessTokenManager